version: "3.8"
services:
  mc-server:
    image: relms/minecraft-server:1.0.0
    container_name: mc-server
    ports:
      - 25565:25565
    restart: "no"
    volumes:
      - "./mc-server:/usr/src/server"