apiVersion: v1
kind: Service
metadata:
  name: minecraft-svc
  labels:
    app: minecraft-svc
  namespace: minecraft
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: minecraft
      port: 25565
      targetPort: minecraft
      protocol: TCP
  selector:
    app: minecraft-server
