kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-pvc
  labels:
    app: minecraft-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: minecraft-sc
