apiVersion: v1
kind: Service
metadata:
  name: minecraft-rcon
  labels:
    app: minecraft-rcon
  namespace: minecraft
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: rcon
      port: 25575
      targetPort: rcon
      protocol: TCP
  selector:
    app: minecraft-server
